name: Lint with Fortitude

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: Fortitude-Lint
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: |
          python -m pip install fortitude-lint
          fortitude check --output-format github *.for